AllCops:
  Exclude:
    - 'bin/*'
    - '*.*'
    - 'vendor/**/*'
    - 'examples/**/*'
  TargetRubyVersion: 2.0

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/WordArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false
