AllCops:
  Exclude:
    - 'bin/*'
    - '*.*'
    - 'vendor/**/*'
    - 'examples/**/*'
  TargetRubyVersion: 2.0

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/AlignHash:
  EnforcedHashRocketStyle: table

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/DotPosition:
  EnforcedStyle: trailing

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Lambda:
  EnforcedStyle: literal

Style/WordArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineIfModifier:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/IndentHeredoc:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false
