sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.0.5.0
  - jruby-9.1.5.0
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: 2.2.6
    - rvm: 2.1.10
    - rvm: jruby-9.0.5.0
