sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.0.5.0
  - jruby-9.1.5.0
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: jruby-9.0.5.0
